import React, { useEffect, useState } from 'react'
import '../../../styles/ModulePage.css'
import '../../../styles/AccountsReports.css'
import '../../../styles/AccountsTheme.css'
import { accountsAPI } from '../../../services/api'

const ReportsPage = () => {
  const [reports, setReports] = useState([])
  const [error, setError] = useState('')

  const fetchReports = async () => {
    try {
      const [trialResponse, profitResponse, balanceResponse] = await Promise.all([
        accountsAPI.getTrialBalance(),
        accountsAPI.getProfitLoss(),
        accountsAPI.getBalanceSheet(),
      ])
      setReports([
        { name: 'Trial Balance', ...trialResponse.data },
        { name: 'Profit & Loss', ...profitResponse.data },
        { name: 'Balance Sheet', ...balanceResponse.data },
      ])
    } catch (err) {
      setError(err.response?.data?.detail || 'Unable to load reports')
    }
  }

  useEffect(() => {
    fetchReports()
  }, [])

  return (
    <div className="module-page">
      <h2>Reports</h2>
      <p>View accounting reports generated by the backend.</p>
      {error && <div className="error-message">{error}</div>}

      <div className="accounts-summary">
        {reports.length === 0 ? (
          <p>No reports available yet.</p>
        ) : (
          <div className="reports-grid">
            {reports.map((report) => (
              <div key={report.name} className="report-card">
                <h3>{report.name}</h3>
                <p><strong>Generated:</strong> {new Date(report.generated_at).toLocaleDateString()}</p>
                {report.name === 'Trial Balance' && (
                  <>
                    <p><strong>Debit:</strong> {report.total_debit}</p>
                    <p><strong>Credit:</strong> {report.total_credit}</p>
                    <p><strong>Balanced:</strong> {report.is_balanced ? 'Yes' : 'No'}</p>
                  </>
                )}
                {report.name === 'Profit & Loss' && (
                  <>
                    <p><strong>Revenue:</strong> {report.revenue}</p>
                    <p><strong>Expenses:</strong> {report.expenses}</p>
                    <p><strong>Net Profit:</strong> {report.net_profit}</p>
                  </>
                )}
                {report.name === 'Balance Sheet' && (
                  <>
                    <p><strong>Assets:</strong> {report.assets}</p>
                    <p><strong>Liabilities:</strong> {report.liabilities}</p>
                    <p><strong>Equity:</strong> {report.equity}</p>
                    <p><strong>Balanced:</strong> {report.is_balanced ? 'Yes' : 'No'}</p>
                  </>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}

export default ReportsPage
